services:
  - type: web
    name: Blog-App
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    preDeployCommand: alembic upgrade head
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT